// Bibliothèque de 30 templates d'exemples
// Du plus simple au plus complexe

export interface TemplateNode {
  id: string;
  type: string;
  x: number;
  y: number;
  properties: Record<string, any>;
}

export interface TemplateConnection {
  fromNode: string;
  fromPortIndex: number;
  toNode: string;
  toPortIndex: number;
}

export interface Template {
  id: string;
  name: string;
  description: string;
  category: 'basics' | 'forms' | 'data' | 'ui' | 'state' | 'apps';
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  tags: string[];
  nodes: TemplateNode[];
  connections: TemplateConnection[];
}

// Port indices reference for common nodes:
// ui-text: inputs = [0:flow, 1:content], outputs = [0:element]
// ui-button: inputs = [0:flow, 1:label, 2:disabled], outputs = [0:onClick, 1:element]
// ui-input: inputs = [0:flow, 1:placeholder, 2:value], outputs = [0:onChange, 1:value, 2:element]
// ui-container: inputs = [0:flow, 1:children], outputs = [0:element]
// ui-image: inputs = [0:flow, 1:src, 2:alt], outputs = [0:element]
// ui-list: inputs = [0:flow, 1:items], outputs = [0:onItemClick, 1:item, 2:element]
// hook-useState: inputs = [0:initialValue], outputs = [0:value, 1:setValue]
// data-string/number/boolean: inputs = [], outputs = [0:value]
// data-array: inputs = [0..9:items], outputs = [0:array]
// math-add/subtract/multiply/divide: inputs = [0:a, 1:b], outputs = [0:result]
// logic-if: inputs = [0:trigger, 1:condition], outputs = [0:true, 1:false]
// logic-compare: inputs = [0:a, 1:b], outputs = [0:result]
// logic-and/or: inputs = [0:a, 1:b], outputs = [0:result]
// logic-not: inputs = [0:input], outputs = [0:result]
// debug-log: inputs = [0:trigger, 1:message], outputs = [0:flow]
// event-start: inputs = [], outputs = [0:flow]

export const TEMPLATES: Template[] = [
  // =============== BASICS (1-6) ===============
  {
    id: 'hello-world',
    name: 'Hello World',
    description: 'Le composant le plus simple: affiche un texte',
    category: 'basics',
    difficulty: 'beginner',
    tags: ['texte', 'débutant', 'simple'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 200, properties: {} },
      { id: 'text', type: 'data-string', x: 100, y: 350, properties: { value: 'Hello World!' } },
      { id: 'display', type: 'ui-text', x: 400, y: 200, properties: { tag: 'h1' } },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'display', toPortIndex: 0 },
      { fromNode: 'text', fromPortIndex: 0, toNode: 'display', toPortIndex: 1 },
    ],
  },

  {
    id: 'button-action',
    name: 'Bouton avec Action',
    description: 'Un bouton qui déclenche un console.log au clic',
    category: 'basics',
    difficulty: 'beginner',
    tags: ['bouton', 'événement', 'clic'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 200, properties: {} },
      { id: 'label', type: 'data-string', x: 100, y: 350, properties: { value: 'Cliquez-moi!' } },
      { id: 'button', type: 'ui-button', x: 400, y: 200, properties: { variant: 'primary' } },
      { id: 'message', type: 'data-string', x: 400, y: 400, properties: { value: 'Bouton cliqué!' } },
      { id: 'log', type: 'debug-log', x: 700, y: 200, properties: {} },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'button', toPortIndex: 0 },
      { fromNode: 'label', fromPortIndex: 0, toNode: 'button', toPortIndex: 1 },
      { fromNode: 'button', fromPortIndex: 0, toNode: 'log', toPortIndex: 0 },
      { fromNode: 'message', fromPortIndex: 0, toNode: 'log', toPortIndex: 1 },
    ],
  },

  {
    id: 'counter',
    name: 'Compteur Simple',
    description: 'Un compteur avec useState, boutons + et -',
    category: 'basics',
    difficulty: 'beginner',
    tags: ['useState', 'compteur', 'état'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 100, properties: {} },
      { id: 'initial', type: 'data-number', x: 100, y: 300, properties: { value: 0 } },
      { id: 'state', type: 'hook-useState', x: 350, y: 200, properties: { name: 'count' } },
      { id: 'container', type: 'ui-container', x: 600, y: 100, properties: { layout: 'flex-row', gap: 4 } },
      { id: 'labelMinus', type: 'data-string', x: 350, y: 450, properties: { value: '-' } },
      { id: 'btnMinus', type: 'ui-button', x: 600, y: 350, properties: { variant: 'secondary' } },
      { id: 'display', type: 'ui-text', x: 850, y: 200, properties: { tag: 'span' } },
      { id: 'labelPlus', type: 'data-string', x: 600, y: 550, properties: { value: '+' } },
      { id: 'btnPlus', type: 'ui-button', x: 850, y: 450, properties: { variant: 'primary' } },
    ],
    connections: [
      // Flow: start -> container
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      // State initialization
      { fromNode: 'initial', fromPortIndex: 0, toNode: 'state', toPortIndex: 0 },
      // Container children - connect container element output to children flow inputs
      { fromNode: 'container', fromPortIndex: 0, toNode: 'btnMinus', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'display', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'btnPlus', toPortIndex: 0 },
      // Button labels
      { fromNode: 'labelMinus', fromPortIndex: 0, toNode: 'btnMinus', toPortIndex: 1 },
      { fromNode: 'labelPlus', fromPortIndex: 0, toNode: 'btnPlus', toPortIndex: 1 },
      // Display state value
      { fromNode: 'state', fromPortIndex: 0, toNode: 'display', toPortIndex: 1 },
    ],
  },

  {
    id: 'toggle-visibility',
    name: 'Toggle Visibilité',
    description: 'Afficher/masquer un élément avec une condition',
    category: 'basics',
    difficulty: 'beginner',
    tags: ['condition', 'toggle', 'visibilité'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 100, properties: {} },
      { id: 'initial', type: 'data-boolean', x: 100, y: 300, properties: { value: true } },
      { id: 'state', type: 'hook-useState', x: 350, y: 200, properties: { name: 'showContent' } },
      { id: 'container', type: 'ui-container', x: 600, y: 100, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'btnLabel', type: 'data-string', x: 350, y: 450, properties: { value: 'Toggle Afficher/Masquer' } },
      { id: 'btn', type: 'ui-button', x: 600, y: 350, properties: { variant: 'primary' } },
      { id: 'if', type: 'logic-if', x: 850, y: 200, properties: {} },
      { id: 'content', type: 'data-string', x: 850, y: 450, properties: { value: '✨ Contenu visible! Cliquez pour masquer.' } },
      { id: 'text', type: 'ui-text', x: 1100, y: 300, properties: { tag: 'p' } },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'initial', fromPortIndex: 0, toNode: 'state', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'btn', toPortIndex: 0 },
      { fromNode: 'btnLabel', fromPortIndex: 0, toNode: 'btn', toPortIndex: 1 },
      { fromNode: 'state', fromPortIndex: 0, toNode: 'if', toPortIndex: 1 },
      { fromNode: 'if', fromPortIndex: 0, toNode: 'text', toPortIndex: 0 },
      { fromNode: 'content', fromPortIndex: 0, toNode: 'text', toPortIndex: 1 },
    ],
  },

  {
    id: 'image-display',
    name: 'Affichage Image',
    description: 'Afficher une image avec source et alt',
    category: 'basics',
    difficulty: 'beginner',
    tags: ['image', 'média', 'affichage'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 200, properties: {} },
      { id: 'src', type: 'data-string', x: 100, y: 350, properties: { value: 'https://picsum.photos/400/300' } },
      { id: 'alt', type: 'data-string', x: 100, y: 500, properties: { value: 'Image aléatoire' } },
      { id: 'image', type: 'ui-image', x: 450, y: 300, properties: {} },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'image', toPortIndex: 0 },
      { fromNode: 'src', fromPortIndex: 0, toNode: 'image', toPortIndex: 1 },
      { fromNode: 'alt', fromPortIndex: 0, toNode: 'image', toPortIndex: 2 },
    ],
  },

  {
    id: 'layout-container',
    name: 'Container & Layout',
    description: 'Organisation de composants avec flex',
    category: 'basics',
    difficulty: 'beginner',
    tags: ['layout', 'flex', 'container'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 150, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 150, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'text1', type: 'data-string', x: 350, y: 350, properties: { value: 'Élément 1' } },
      { id: 'ui1', type: 'ui-text', x: 600, y: 250, properties: { tag: 'p' } },
      { id: 'text2', type: 'data-string', x: 600, y: 450, properties: { value: 'Élément 2' } },
      { id: 'ui2', type: 'ui-text', x: 850, y: 350, properties: { tag: 'p' } },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'ui1', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'ui2', toPortIndex: 0 },
      { fromNode: 'text1', fromPortIndex: 0, toNode: 'ui1', toPortIndex: 1 },
      { fromNode: 'text2', fromPortIndex: 0, toNode: 'ui2', toPortIndex: 1 },
    ],
  },

  // =============== FORMS (7-12) ===============
  {
    id: 'text-input',
    name: 'Champ de Texte',
    description: 'Input contrôlé avec état',
    category: 'forms',
    difficulty: 'beginner',
    tags: ['input', 'formulaire', 'texte'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 100, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 100, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'initial', type: 'data-string', x: 100, y: 300, properties: { value: '' } },
      { id: 'state', type: 'hook-useState', x: 350, y: 300, properties: { name: 'text' } },
      { id: 'placeholder', type: 'data-string', x: 350, y: 500, properties: { value: 'Tapez ici...' } },
      { id: 'input', type: 'ui-input', x: 600, y: 250, properties: {} },
      { id: 'previewLabel', type: 'data-string', x: 600, y: 500, properties: { value: 'Vous avez tapé: ' } },
      { id: 'concat', type: 'data-concat', x: 850, y: 400, properties: {} },
      { id: 'preview', type: 'ui-text', x: 1100, y: 350, properties: { tag: 'p' } },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'input', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'preview', toPortIndex: 0 },
      { fromNode: 'initial', fromPortIndex: 0, toNode: 'state', toPortIndex: 0 },
      { fromNode: 'placeholder', fromPortIndex: 0, toNode: 'input', toPortIndex: 1 },
      { fromNode: 'state', fromPortIndex: 0, toNode: 'input', toPortIndex: 2 },
      { fromNode: 'previewLabel', fromPortIndex: 0, toNode: 'concat', toPortIndex: 0 },
      { fromNode: 'state', fromPortIndex: 0, toNode: 'concat', toPortIndex: 1 },
      { fromNode: 'concat', fromPortIndex: 0, toNode: 'preview', toPortIndex: 1 },
    ],
  },

  {
    id: 'login-form',
    name: 'Formulaire Login',
    description: 'Formulaire avec email et mot de passe',
    category: 'forms',
    difficulty: 'intermediate',
    tags: ['login', 'formulaire', 'authentification'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 100, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 100, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'title', type: 'data-string', x: 100, y: 300, properties: { value: 'Connexion' } },
      { id: 'titleUi', type: 'ui-text', x: 350, y: 250, properties: { tag: 'h2' } },
      { id: 'emailInit', type: 'data-string', x: 100, y: 450, properties: { value: '' } },
      { id: 'emailState', type: 'hook-useState', x: 350, y: 450, properties: { name: 'email' } },
      { id: 'emailPh', type: 'data-string', x: 350, y: 600, properties: { value: 'Email' } },
      { id: 'emailInput', type: 'ui-input', x: 600, y: 350, properties: {} },
      { id: 'passInit', type: 'data-string', x: 100, y: 750, properties: { value: '' } },
      { id: 'passState', type: 'hook-useState', x: 350, y: 750, properties: { name: 'password' } },
      { id: 'passPh', type: 'data-string', x: 350, y: 900, properties: { value: 'Mot de passe' } },
      { id: 'passInput', type: 'ui-input', x: 600, y: 650, properties: {} },
      { id: 'btnLabel', type: 'data-string', x: 600, y: 900, properties: { value: 'Se connecter' } },
      { id: 'submitBtn', type: 'ui-button', x: 850, y: 800, properties: { variant: 'primary' } },
      { id: 'log', type: 'debug-log', x: 1100, y: 800, properties: {} },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'titleUi', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'emailInput', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'passInput', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'submitBtn', toPortIndex: 0 },
      { fromNode: 'title', fromPortIndex: 0, toNode: 'titleUi', toPortIndex: 1 },
      { fromNode: 'emailInit', fromPortIndex: 0, toNode: 'emailState', toPortIndex: 0 },
      { fromNode: 'emailPh', fromPortIndex: 0, toNode: 'emailInput', toPortIndex: 1 },
      { fromNode: 'emailState', fromPortIndex: 0, toNode: 'emailInput', toPortIndex: 2 },
      { fromNode: 'passInit', fromPortIndex: 0, toNode: 'passState', toPortIndex: 0 },
      { fromNode: 'passPh', fromPortIndex: 0, toNode: 'passInput', toPortIndex: 1 },
      { fromNode: 'passState', fromPortIndex: 0, toNode: 'passInput', toPortIndex: 2 },
      { fromNode: 'btnLabel', fromPortIndex: 0, toNode: 'submitBtn', toPortIndex: 1 },
      { fromNode: 'submitBtn', fromPortIndex: 0, toNode: 'log', toPortIndex: 0 },
      { fromNode: 'emailState', fromPortIndex: 0, toNode: 'log', toPortIndex: 1 },
    ],
  },

  {
    id: 'search-filter',
    name: 'Recherche & Filtre',
    description: 'Filtrer une liste avec un champ de recherche',
    category: 'forms',
    difficulty: 'intermediate',
    tags: ['recherche', 'filtre', 'liste'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 100, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 100, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'searchInit', type: 'data-string', x: 100, y: 300, properties: { value: '' } },
      { id: 'searchState', type: 'hook-useState', x: 350, y: 300, properties: { name: 'search' } },
      { id: 'searchPh', type: 'data-string', x: 350, y: 500, properties: { value: 'Rechercher...' } },
      { id: 'searchInput', type: 'ui-input', x: 600, y: 250, properties: {} },
      { id: 'item1', type: 'data-string', x: 100, y: 600, properties: { value: 'Pomme' } },
      { id: 'item2', type: 'data-string', x: 100, y: 700, properties: { value: 'Banane' } },
      { id: 'item3', type: 'data-string', x: 100, y: 800, properties: { value: 'Orange' } },
      { id: 'item4', type: 'data-string', x: 100, y: 900, properties: { value: 'Fraise' } },
      { id: 'item5', type: 'data-string', x: 100, y: 1000, properties: { value: 'Cerise' } },
      { id: 'items', type: 'data-array', x: 350, y: 750, properties: {} },
      { id: 'filter', type: 'array-filter', x: 600, y: 600, properties: {} },
      { id: 'list', type: 'ui-list', x: 850, y: 450, properties: {} },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'searchInput', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'list', toPortIndex: 0 },
      { fromNode: 'searchInit', fromPortIndex: 0, toNode: 'searchState', toPortIndex: 0 },
      { fromNode: 'searchPh', fromPortIndex: 0, toNode: 'searchInput', toPortIndex: 1 },
      { fromNode: 'searchState', fromPortIndex: 0, toNode: 'searchInput', toPortIndex: 2 },
      { fromNode: 'item1', fromPortIndex: 0, toNode: 'items', toPortIndex: 0 },
      { fromNode: 'item2', fromPortIndex: 0, toNode: 'items', toPortIndex: 1 },
      { fromNode: 'item3', fromPortIndex: 0, toNode: 'items', toPortIndex: 2 },
      { fromNode: 'item4', fromPortIndex: 0, toNode: 'items', toPortIndex: 3 },
      { fromNode: 'item5', fromPortIndex: 0, toNode: 'items', toPortIndex: 4 },
      { fromNode: 'items', fromPortIndex: 0, toNode: 'filter', toPortIndex: 0 },
      { fromNode: 'searchState', fromPortIndex: 0, toNode: 'filter', toPortIndex: 1 },
      { fromNode: 'filter', fromPortIndex: 0, toNode: 'list', toPortIndex: 1 },
    ],
  },

  {
    id: 'multi-field-form',
    name: 'Formulaire Multi-Champs',
    description: 'Formulaire avec plusieurs inputs (nom, email, message)',
    category: 'forms',
    difficulty: 'intermediate',
    tags: ['formulaire', 'multi-champs', 'contact'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 100, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 100, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'title', type: 'data-string', x: 100, y: 250, properties: { value: 'Contact' } },
      { id: 'titleUi', type: 'ui-text', x: 350, y: 250, properties: { tag: 'h2' } },
      { id: 'nameInit', type: 'data-string', x: 100, y: 400, properties: { value: '' } },
      { id: 'nameState', type: 'hook-useState', x: 350, y: 400, properties: { name: 'name' } },
      { id: 'namePh', type: 'data-string', x: 350, y: 550, properties: { value: 'Votre nom' } },
      { id: 'nameInput', type: 'ui-input', x: 600, y: 350, properties: {} },
      { id: 'emailInit', type: 'data-string', x: 100, y: 700, properties: { value: '' } },
      { id: 'emailState', type: 'hook-useState', x: 350, y: 700, properties: { name: 'email' } },
      { id: 'emailPh', type: 'data-string', x: 350, y: 850, properties: { value: 'Votre email' } },
      { id: 'emailInput', type: 'ui-input', x: 600, y: 650, properties: {} },
      { id: 'msgInit', type: 'data-string', x: 100, y: 1000, properties: { value: '' } },
      { id: 'msgState', type: 'hook-useState', x: 350, y: 1000, properties: { name: 'message' } },
      { id: 'msgPh', type: 'data-string', x: 350, y: 1150, properties: { value: 'Votre message' } },
      { id: 'msgInput', type: 'ui-input', x: 600, y: 950, properties: {} },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'titleUi', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'nameInput', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'emailInput', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'msgInput', toPortIndex: 0 },
      { fromNode: 'title', fromPortIndex: 0, toNode: 'titleUi', toPortIndex: 1 },
      { fromNode: 'nameInit', fromPortIndex: 0, toNode: 'nameState', toPortIndex: 0 },
      { fromNode: 'namePh', fromPortIndex: 0, toNode: 'nameInput', toPortIndex: 1 },
      { fromNode: 'nameState', fromPortIndex: 0, toNode: 'nameInput', toPortIndex: 2 },
      { fromNode: 'emailInit', fromPortIndex: 0, toNode: 'emailState', toPortIndex: 0 },
      { fromNode: 'emailPh', fromPortIndex: 0, toNode: 'emailInput', toPortIndex: 1 },
      { fromNode: 'emailState', fromPortIndex: 0, toNode: 'emailInput', toPortIndex: 2 },
      { fromNode: 'msgInit', fromPortIndex: 0, toNode: 'msgState', toPortIndex: 0 },
      { fromNode: 'msgPh', fromPortIndex: 0, toNode: 'msgInput', toPortIndex: 1 },
      { fromNode: 'msgState', fromPortIndex: 0, toNode: 'msgInput', toPortIndex: 2 },
    ],
  },

  {
    id: 'numeric-input',
    name: 'Input Numérique',
    description: 'Calculs en temps réel avec un nombre (double)',
    category: 'forms',
    difficulty: 'intermediate',
    tags: ['nombre', 'calcul', 'temps réel'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 100, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 100, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'numInit', type: 'data-number', x: 100, y: 300, properties: { value: 10 } },
      { id: 'numState', type: 'hook-useState', x: 350, y: 300, properties: { name: 'number' } },
      { id: 'numPh', type: 'data-string', x: 350, y: 500, properties: { value: 'Entrez un nombre' } },
      { id: 'numInput', type: 'ui-input', x: 600, y: 250, properties: {} },
      { id: 'two', type: 'data-number', x: 600, y: 500, properties: { value: 2 } },
      { id: 'double', type: 'math-multiply', x: 850, y: 350, properties: {} },
      { id: 'resultLabel', type: 'data-string', x: 850, y: 550, properties: { value: 'Le double est: ' } },
      { id: 'concat', type: 'data-concat', x: 1100, y: 450, properties: {} },
      { id: 'resultText', type: 'ui-text', x: 1350, y: 400, properties: { tag: 'p' } },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'numInput', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'resultText', toPortIndex: 0 },
      { fromNode: 'numInit', fromPortIndex: 0, toNode: 'numState', toPortIndex: 0 },
      { fromNode: 'numPh', fromPortIndex: 0, toNode: 'numInput', toPortIndex: 1 },
      { fromNode: 'numState', fromPortIndex: 0, toNode: 'numInput', toPortIndex: 2 },
      { fromNode: 'numState', fromPortIndex: 0, toNode: 'double', toPortIndex: 0 },
      { fromNode: 'two', fromPortIndex: 0, toNode: 'double', toPortIndex: 1 },
      { fromNode: 'resultLabel', fromPortIndex: 0, toNode: 'concat', toPortIndex: 0 },
      { fromNode: 'double', fromPortIndex: 0, toNode: 'concat', toPortIndex: 1 },
      { fromNode: 'concat', fromPortIndex: 0, toNode: 'resultText', toPortIndex: 1 },
    ],
  },

  {
    id: 'form-validation',
    name: 'Validation Formulaire',
    description: 'Validation avec feedback visuel',
    category: 'forms',
    difficulty: 'advanced',
    tags: ['validation', 'erreur', 'feedback'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 100, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 100, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'emailInit', type: 'data-string', x: 100, y: 300, properties: { value: '' } },
      { id: 'emailState', type: 'hook-useState', x: 350, y: 300, properties: { name: 'email' } },
      { id: 'emailPh', type: 'data-string', x: 350, y: 500, properties: { value: 'Entrez votre email' } },
      { id: 'emailInput', type: 'ui-input', x: 600, y: 250, properties: {} },
      { id: 'empty', type: 'data-string', x: 600, y: 500, properties: { value: '' } },
      { id: 'compare', type: 'logic-compare', x: 850, y: 350, properties: { operator: '!==' } },
      { id: 'if', type: 'logic-if', x: 1100, y: 300, properties: {} },
      { id: 'validMsg', type: 'data-string', x: 1100, y: 500, properties: { value: '✓ Email renseigné' } },
      { id: 'validText', type: 'ui-text', x: 1350, y: 350, properties: { tag: 'span' } },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'emailInput', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'validText', toPortIndex: 0 },
      { fromNode: 'emailInit', fromPortIndex: 0, toNode: 'emailState', toPortIndex: 0 },
      { fromNode: 'emailPh', fromPortIndex: 0, toNode: 'emailInput', toPortIndex: 1 },
      { fromNode: 'emailState', fromPortIndex: 0, toNode: 'emailInput', toPortIndex: 2 },
      { fromNode: 'emailState', fromPortIndex: 0, toNode: 'compare', toPortIndex: 0 },
      { fromNode: 'empty', fromPortIndex: 0, toNode: 'compare', toPortIndex: 1 },
      { fromNode: 'compare', fromPortIndex: 0, toNode: 'if', toPortIndex: 1 },
      { fromNode: 'if', fromPortIndex: 0, toNode: 'validText', toPortIndex: 0 },
      { fromNode: 'validMsg', fromPortIndex: 0, toNode: 'validText', toPortIndex: 1 },
    ],
  },

  // =============== DATA (13-18) ===============
  {
    id: 'fetch-api',
    name: 'Fetch API',
    description: 'Charger des données depuis une API REST',
    category: 'data',
    difficulty: 'intermediate',
    tags: ['fetch', 'API', 'async'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 100, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 100, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'title', type: 'data-string', x: 100, y: 300, properties: { value: 'Données API' } },
      { id: 'titleUi', type: 'ui-text', x: 350, y: 250, properties: { tag: 'h2' } },
      { id: 'url', type: 'data-string', x: 100, y: 500, properties: { value: 'https://jsonplaceholder.typicode.com/posts/1' } },
      { id: 'fetch', type: 'async-fetch', x: 400, y: 450, properties: { method: 'GET' } },
      { id: 'text', type: 'ui-text', x: 700, y: 300, properties: { tag: 'pre' } },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'titleUi', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'text', toPortIndex: 0 },
      { fromNode: 'title', fromPortIndex: 0, toNode: 'titleUi', toPortIndex: 1 },
      { fromNode: 'url', fromPortIndex: 0, toNode: 'fetch', toPortIndex: 1 },
      { fromNode: 'fetch', fromPortIndex: 2, toNode: 'text', toPortIndex: 1 },
    ],
  },

  {
    id: 'data-list',
    name: 'Liste de Données',
    description: 'Afficher une liste avec ui-list',
    category: 'data',
    difficulty: 'beginner',
    tags: ['liste', 'array', 'affichage'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 150, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 150, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'title', type: 'data-string', x: 100, y: 350, properties: { value: 'Ma Liste' } },
      { id: 'titleUi', type: 'ui-text', x: 350, y: 300, properties: { tag: 'h2' } },
      { id: 'item1', type: 'data-string', x: 100, y: 500, properties: { value: 'Premier élément' } },
      { id: 'item2', type: 'data-string', x: 100, y: 600, properties: { value: 'Deuxième élément' } },
      { id: 'item3', type: 'data-string', x: 100, y: 700, properties: { value: 'Troisième élément' } },
      { id: 'array', type: 'data-array', x: 400, y: 550, properties: {} },
      { id: 'list', type: 'ui-list', x: 650, y: 450, properties: {} },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'titleUi', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'list', toPortIndex: 0 },
      { fromNode: 'title', fromPortIndex: 0, toNode: 'titleUi', toPortIndex: 1 },
      { fromNode: 'item1', fromPortIndex: 0, toNode: 'array', toPortIndex: 0 },
      { fromNode: 'item2', fromPortIndex: 0, toNode: 'array', toPortIndex: 1 },
      { fromNode: 'item3', fromPortIndex: 0, toNode: 'array', toPortIndex: 2 },
      { fromNode: 'array', fromPortIndex: 0, toNode: 'list', toPortIndex: 1 },
    ],
  },

  {
    id: 'array-operations',
    name: 'Opérations sur Array',
    description: 'Doubler chaque élément d\'un tableau',
    category: 'data',
    difficulty: 'intermediate',
    tags: ['array', 'map', 'calcul'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 150, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 150, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'title', type: 'data-string', x: 100, y: 350, properties: { value: 'Nombres: 1, 2, 3' } },
      { id: 'titleUi', type: 'ui-text', x: 350, y: 300, properties: { tag: 'p' } },
      { id: 'n1', type: 'data-number', x: 100, y: 500, properties: { value: 1 } },
      { id: 'n2', type: 'data-number', x: 100, y: 600, properties: { value: 2 } },
      { id: 'n3', type: 'data-number', x: 100, y: 700, properties: { value: 3 } },
      { id: 'array', type: 'data-array', x: 350, y: 550, properties: {} },
      { id: 'list', type: 'ui-list', x: 600, y: 450, properties: {} },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'titleUi', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'list', toPortIndex: 0 },
      { fromNode: 'title', fromPortIndex: 0, toNode: 'titleUi', toPortIndex: 1 },
      { fromNode: 'n1', fromPortIndex: 0, toNode: 'array', toPortIndex: 0 },
      { fromNode: 'n2', fromPortIndex: 0, toNode: 'array', toPortIndex: 1 },
      { fromNode: 'n3', fromPortIndex: 0, toNode: 'array', toPortIndex: 2 },
      { fromNode: 'array', fromPortIndex: 0, toNode: 'list', toPortIndex: 1 },
    ],
  },

  {
    id: 'object-manipulation',
    name: 'Manipulation Objets',
    description: 'Get et Set de propriétés d\'objet',
    category: 'data',
    difficulty: 'intermediate',
    tags: ['objet', 'propriété', 'get', 'set'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 200, properties: {} },
      { id: 'object', type: 'data-object', x: 100, y: 400, properties: { fields: 'name,age' } },
      { id: 'key', type: 'data-string', x: 100, y: 550, properties: { value: 'name' } },
      { id: 'get', type: 'data-get', x: 400, y: 450, properties: {} },
      { id: 'text', type: 'ui-text', x: 650, y: 350, properties: { tag: 'p' } },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'text', toPortIndex: 0 },
      { fromNode: 'object', fromPortIndex: 0, toNode: 'get', toPortIndex: 0 },
      { fromNode: 'key', fromPortIndex: 0, toNode: 'get', toPortIndex: 1 },
      { fromNode: 'get', fromPortIndex: 0, toNode: 'text', toPortIndex: 1 },
    ],
  },

  {
    id: 'local-storage',
    name: 'LocalStorage',
    description: 'Sauvegarder des données localement',
    category: 'data',
    difficulty: 'advanced',
    tags: ['localStorage', 'persistance', 'sauvegarde'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 100, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 100, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'init', type: 'data-string', x: 100, y: 300, properties: { value: '' } },
      { id: 'state', type: 'hook-useState', x: 350, y: 300, properties: { name: 'saved' } },
      { id: 'ph', type: 'data-string', x: 350, y: 500, properties: { value: 'Données à sauvegarder' } },
      { id: 'input', type: 'ui-input', x: 600, y: 250, properties: {} },
      { id: 'saveLabel', type: 'data-string', x: 600, y: 500, properties: { value: 'Sauvegarder' } },
      { id: 'saveBtn', type: 'ui-button', x: 850, y: 400, properties: { variant: 'primary' } },
      { id: 'log', type: 'debug-log', x: 1100, y: 400, properties: {} },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'input', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'saveBtn', toPortIndex: 0 },
      { fromNode: 'init', fromPortIndex: 0, toNode: 'state', toPortIndex: 0 },
      { fromNode: 'ph', fromPortIndex: 0, toNode: 'input', toPortIndex: 1 },
      { fromNode: 'state', fromPortIndex: 0, toNode: 'input', toPortIndex: 2 },
      { fromNode: 'saveLabel', fromPortIndex: 0, toNode: 'saveBtn', toPortIndex: 1 },
      { fromNode: 'saveBtn', fromPortIndex: 0, toNode: 'log', toPortIndex: 0 },
      { fromNode: 'state', fromPortIndex: 0, toNode: 'log', toPortIndex: 1 },
    ],
  },

  {
    id: 'async-delay',
    name: 'Async & Delay',
    description: 'Opérations asynchrones avec délai',
    category: 'data',
    difficulty: 'intermediate',
    tags: ['async', 'delay', 'timeout'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 100, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 100, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'btnLabel', type: 'data-string', x: 100, y: 300, properties: { value: 'Démarrer (2s)' } },
      { id: 'btn', type: 'ui-button', x: 350, y: 250, properties: { variant: 'primary' } },
      { id: 'ms', type: 'data-number', x: 350, y: 450, properties: { value: 2000 } },
      { id: 'delay', type: 'async-delay', x: 600, y: 350, properties: { duration: 2000 } },
      { id: 'msg', type: 'data-string', x: 600, y: 550, properties: { value: 'Délai terminé!' } },
      { id: 'log', type: 'debug-log', x: 850, y: 450, properties: {} },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'btn', toPortIndex: 0 },
      { fromNode: 'btnLabel', fromPortIndex: 0, toNode: 'btn', toPortIndex: 1 },
      { fromNode: 'btn', fromPortIndex: 0, toNode: 'delay', toPortIndex: 0 },
      { fromNode: 'ms', fromPortIndex: 0, toNode: 'delay', toPortIndex: 1 },
      { fromNode: 'delay', fromPortIndex: 0, toNode: 'log', toPortIndex: 0 },
      { fromNode: 'msg', fromPortIndex: 0, toNode: 'log', toPortIndex: 1 },
    ],
  },

  // =============== UI (19-24) ===============
  {
    id: 'conditional-render',
    name: 'Rendu Conditionnel',
    description: 'If/Else visuel pour affichage conditionnel',
    category: 'ui',
    difficulty: 'beginner',
    tags: ['condition', 'if', 'else'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 150, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 150, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'init', type: 'data-boolean', x: 100, y: 350, properties: { value: true } },
      { id: 'state', type: 'hook-useState', x: 350, y: 350, properties: { name: 'showA' } },
      { id: 'if', type: 'logic-if', x: 600, y: 300, properties: {} },
      { id: 'textA', type: 'data-string', x: 600, y: 500, properties: { value: 'Version A (true)' } },
      { id: 'uiA', type: 'ui-text', x: 850, y: 250, properties: { tag: 'h2' } },
      { id: 'textB', type: 'data-string', x: 850, y: 500, properties: { value: 'Version B (false)' } },
      { id: 'uiB', type: 'ui-text', x: 1100, y: 400, properties: { tag: 'h2' } },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'uiA', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'uiB', toPortIndex: 0 },
      { fromNode: 'init', fromPortIndex: 0, toNode: 'state', toPortIndex: 0 },
      { fromNode: 'state', fromPortIndex: 0, toNode: 'if', toPortIndex: 1 },
      { fromNode: 'if', fromPortIndex: 0, toNode: 'uiA', toPortIndex: 0 },
      { fromNode: 'textA', fromPortIndex: 0, toNode: 'uiA', toPortIndex: 1 },
      { fromNode: 'if', fromPortIndex: 1, toNode: 'uiB', toPortIndex: 0 },
      { fromNode: 'textB', fromPortIndex: 0, toNode: 'uiB', toPortIndex: 1 },
    ],
  },

  {
    id: 'switch-views',
    name: 'Switch / Case',
    description: 'Navigation entre plusieurs vues',
    category: 'ui',
    difficulty: 'intermediate',
    tags: ['switch', 'navigation', 'tabs'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 100, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 100, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'init', type: 'data-number', x: 100, y: 300, properties: { value: 1 } },
      { id: 'tabState', type: 'hook-useState', x: 350, y: 300, properties: { name: 'activeTab' } },
      { id: 'tabLabel', type: 'data-string', x: 350, y: 150, properties: { value: 'Onglet actif: ' } },
      { id: 'concat', type: 'data-concat', x: 600, y: 200, properties: {} },
      { id: 'display', type: 'ui-text', x: 850, y: 200, properties: { tag: 'h2' } },
      { id: 'btnRow', type: 'ui-container', x: 600, y: 400, properties: { layout: 'flex-row', gap: 2 } },
      { id: 'label1', type: 'data-string', x: 350, y: 550, properties: { value: 'Tab 1' } },
      { id: 'btn1', type: 'ui-button', x: 600, y: 550, properties: { variant: 'primary' } },
      { id: 'label2', type: 'data-string', x: 850, y: 550, properties: { value: 'Tab 2' } },
      { id: 'btn2', type: 'ui-button', x: 1000, y: 550, properties: { variant: 'secondary' } },
      { id: 'label3', type: 'data-string', x: 1100, y: 550, properties: { value: 'Tab 3' } },
      { id: 'btn3', type: 'ui-button', x: 1250, y: 550, properties: { variant: 'secondary' } },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'display', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'btnRow', toPortIndex: 0 },
      { fromNode: 'btnRow', fromPortIndex: 0, toNode: 'btn1', toPortIndex: 0 },
      { fromNode: 'btnRow', fromPortIndex: 0, toNode: 'btn2', toPortIndex: 0 },
      { fromNode: 'btnRow', fromPortIndex: 0, toNode: 'btn3', toPortIndex: 0 },
      { fromNode: 'init', fromPortIndex: 0, toNode: 'tabState', toPortIndex: 0 },
      { fromNode: 'tabLabel', fromPortIndex: 0, toNode: 'concat', toPortIndex: 0 },
      { fromNode: 'tabState', fromPortIndex: 0, toNode: 'concat', toPortIndex: 1 },
      { fromNode: 'concat', fromPortIndex: 0, toNode: 'display', toPortIndex: 1 },
      { fromNode: 'label1', fromPortIndex: 0, toNode: 'btn1', toPortIndex: 1 },
      { fromNode: 'label2', fromPortIndex: 0, toNode: 'btn2', toPortIndex: 1 },
      { fromNode: 'label3', fromPortIndex: 0, toNode: 'btn3', toPortIndex: 1 },
    ],
  },

  {
    id: 'dynamic-list',
    name: 'Liste Dynamique',
    description: 'CRUD basique sur une liste',
    category: 'ui',
    difficulty: 'advanced',
    tags: ['liste', 'CRUD', 'dynamique'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 100, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 100, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'title', type: 'data-string', x: 100, y: 250, properties: { value: '📋 Liste Dynamique' } },
      { id: 'titleUi', type: 'ui-text', x: 350, y: 250, properties: { tag: 'h2' } },
      { id: 'item1', type: 'data-string', x: 50, y: 400, properties: { value: 'Premier élément' } },
      { id: 'item2', type: 'data-string', x: 50, y: 500, properties: { value: 'Deuxième élément' } },
      { id: 'itemsInit', type: 'data-array', x: 200, y: 450, properties: {} },
      { id: 'itemsState', type: 'hook-useState', x: 400, y: 400, properties: { name: 'items' } },
      { id: 'inputInit', type: 'data-string', x: 100, y: 600, properties: { value: '' } },
      { id: 'inputState', type: 'hook-useState', x: 350, y: 600, properties: { name: 'newItem' } },
      { id: 'inputPh', type: 'data-string', x: 350, y: 750, properties: { value: 'Nouvel élément...' } },
      { id: 'inputRow', type: 'ui-container', x: 650, y: 550, properties: { layout: 'flex-row', gap: 2 } },
      { id: 'input', type: 'ui-input', x: 900, y: 500, properties: {} },
      { id: 'addLabel', type: 'data-string', x: 900, y: 700, properties: { value: 'Ajouter' } },
      { id: 'addBtn', type: 'ui-button', x: 1150, y: 600, properties: { variant: 'primary' } },
      { id: 'list', type: 'ui-list', x: 650, y: 350, properties: {} },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'titleUi', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'list', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'inputRow', toPortIndex: 0 },
      { fromNode: 'inputRow', fromPortIndex: 0, toNode: 'input', toPortIndex: 0 },
      { fromNode: 'inputRow', fromPortIndex: 0, toNode: 'addBtn', toPortIndex: 0 },
      { fromNode: 'title', fromPortIndex: 0, toNode: 'titleUi', toPortIndex: 1 },
      { fromNode: 'item1', fromPortIndex: 0, toNode: 'itemsInit', toPortIndex: 0 },
      { fromNode: 'item2', fromPortIndex: 0, toNode: 'itemsInit', toPortIndex: 1 },
      { fromNode: 'itemsInit', fromPortIndex: 0, toNode: 'itemsState', toPortIndex: 0 },
      { fromNode: 'inputInit', fromPortIndex: 0, toNode: 'inputState', toPortIndex: 0 },
      { fromNode: 'inputPh', fromPortIndex: 0, toNode: 'input', toPortIndex: 1 },
      { fromNode: 'inputState', fromPortIndex: 0, toNode: 'input', toPortIndex: 2 },
      { fromNode: 'addLabel', fromPortIndex: 0, toNode: 'addBtn', toPortIndex: 1 },
      { fromNode: 'itemsState', fromPortIndex: 0, toNode: 'list', toPortIndex: 1 },
    ],
  },

  {
    id: 'compare-values',
    name: 'Comparaison Valeurs',
    description: 'Utiliser les opérateurs de comparaison',
    category: 'ui',
    difficulty: 'beginner',
    tags: ['comparaison', 'opérateur', 'logique'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 100, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 100, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'a', type: 'data-number', x: 100, y: 300, properties: { value: 10 } },
      { id: 'b', type: 'data-number', x: 100, y: 450, properties: { value: 5 } },
      { id: 'compare', type: 'logic-compare', x: 350, y: 350, properties: { operator: '>' } },
      { id: 'if', type: 'logic-if', x: 600, y: 300, properties: {} },
      { id: 'trueText', type: 'data-string', x: 600, y: 500, properties: { value: '10 > 5 : Vrai!' } },
      { id: 'trueUi', type: 'ui-text', x: 850, y: 250, properties: { tag: 'p' } },
      { id: 'falseText', type: 'data-string', x: 850, y: 500, properties: { value: '10 > 5 : Faux!' } },
      { id: 'falseUi', type: 'ui-text', x: 1100, y: 400, properties: { tag: 'p' } },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'trueUi', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'falseUi', toPortIndex: 0 },
      { fromNode: 'a', fromPortIndex: 0, toNode: 'compare', toPortIndex: 0 },
      { fromNode: 'b', fromPortIndex: 0, toNode: 'compare', toPortIndex: 1 },
      { fromNode: 'compare', fromPortIndex: 0, toNode: 'if', toPortIndex: 1 },
      { fromNode: 'if', fromPortIndex: 0, toNode: 'trueUi', toPortIndex: 0 },
      { fromNode: 'trueText', fromPortIndex: 0, toNode: 'trueUi', toPortIndex: 1 },
      { fromNode: 'if', fromPortIndex: 1, toNode: 'falseUi', toPortIndex: 0 },
      { fromNode: 'falseText', fromPortIndex: 0, toNode: 'falseUi', toPortIndex: 1 },
    ],
  },

  {
    id: 'boolean-logic',
    name: 'Logique Booléenne',
    description: 'AND, OR, NOT combinés',
    category: 'ui',
    difficulty: 'intermediate',
    tags: ['boolean', 'AND', 'OR', 'NOT'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 100, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 100, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'a', type: 'data-boolean', x: 100, y: 300, properties: { value: true } },
      { id: 'b', type: 'data-boolean', x: 100, y: 450, properties: { value: false } },
      { id: 'and', type: 'logic-and', x: 350, y: 300, properties: {} },
      { id: 'or', type: 'logic-or', x: 350, y: 450, properties: {} },
      { id: 'notA', type: 'logic-not', x: 350, y: 600, properties: {} },
      { id: 'andLabel', type: 'data-string', x: 600, y: 200, properties: { value: 'true AND false = ' } },
      { id: 'andConcat', type: 'data-concat', x: 850, y: 250, properties: {} },
      { id: 'andText', type: 'ui-text', x: 1100, y: 200, properties: { tag: 'p' } },
      { id: 'orLabel', type: 'data-string', x: 600, y: 400, properties: { value: 'true OR false = ' } },
      { id: 'orConcat', type: 'data-concat', x: 850, y: 450, properties: {} },
      { id: 'orText', type: 'ui-text', x: 1100, y: 400, properties: { tag: 'p' } },
      { id: 'notLabel', type: 'data-string', x: 600, y: 600, properties: { value: 'NOT true = ' } },
      { id: 'notConcat', type: 'data-concat', x: 850, y: 650, properties: {} },
      { id: 'notText', type: 'ui-text', x: 1100, y: 600, properties: { tag: 'p' } },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'andText', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'orText', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'notText', toPortIndex: 0 },
      { fromNode: 'a', fromPortIndex: 0, toNode: 'and', toPortIndex: 0 },
      { fromNode: 'b', fromPortIndex: 0, toNode: 'and', toPortIndex: 1 },
      { fromNode: 'a', fromPortIndex: 0, toNode: 'or', toPortIndex: 0 },
      { fromNode: 'b', fromPortIndex: 0, toNode: 'or', toPortIndex: 1 },
      { fromNode: 'a', fromPortIndex: 0, toNode: 'notA', toPortIndex: 0 },
      { fromNode: 'andLabel', fromPortIndex: 0, toNode: 'andConcat', toPortIndex: 0 },
      { fromNode: 'and', fromPortIndex: 0, toNode: 'andConcat', toPortIndex: 1 },
      { fromNode: 'andConcat', fromPortIndex: 0, toNode: 'andText', toPortIndex: 1 },
      { fromNode: 'orLabel', fromPortIndex: 0, toNode: 'orConcat', toPortIndex: 0 },
      { fromNode: 'or', fromPortIndex: 0, toNode: 'orConcat', toPortIndex: 1 },
      { fromNode: 'orConcat', fromPortIndex: 0, toNode: 'orText', toPortIndex: 1 },
      { fromNode: 'notLabel', fromPortIndex: 0, toNode: 'notConcat', toPortIndex: 0 },
      { fromNode: 'notA', fromPortIndex: 0, toNode: 'notConcat', toPortIndex: 1 },
      { fromNode: 'notConcat', fromPortIndex: 0, toNode: 'notText', toPortIndex: 1 },
    ],
  },

  {
    id: 'string-concat',
    name: 'Concaténation',
    description: 'Combiner des chaînes de caractères',
    category: 'ui',
    difficulty: 'beginner',
    tags: ['string', 'concat', 'texte'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 100, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 100, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'hello', type: 'data-string', x: 100, y: 300, properties: { value: 'Bonjour, ' } },
      { id: 'nameInit', type: 'data-string', x: 100, y: 450, properties: { value: '' } },
      { id: 'nameState', type: 'hook-useState', x: 350, y: 400, properties: { name: 'name' } },
      { id: 'ph', type: 'data-string', x: 350, y: 550, properties: { value: 'Votre nom' } },
      { id: 'input', type: 'ui-input', x: 600, y: 350, properties: {} },
      { id: 'concat', type: 'data-concat', x: 600, y: 200, properties: {} },
      { id: 'result', type: 'ui-text', x: 850, y: 200, properties: { tag: 'h2' } },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'result', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'input', toPortIndex: 0 },
      { fromNode: 'nameInit', fromPortIndex: 0, toNode: 'nameState', toPortIndex: 0 },
      { fromNode: 'ph', fromPortIndex: 0, toNode: 'input', toPortIndex: 1 },
      { fromNode: 'nameState', fromPortIndex: 0, toNode: 'input', toPortIndex: 2 },
      { fromNode: 'hello', fromPortIndex: 0, toNode: 'concat', toPortIndex: 0 },
      { fromNode: 'nameState', fromPortIndex: 0, toNode: 'concat', toPortIndex: 1 },
      { fromNode: 'concat', fromPortIndex: 0, toNode: 'result', toPortIndex: 1 },
    ],
  },

  // =============== STATE (25-27) ===============
  {
    id: 'use-ref-dom',
    name: 'useRef & DOM',
    description: 'Référencer et manipuler le DOM',
    category: 'state',
    difficulty: 'intermediate',
    tags: ['useRef', 'DOM', 'référence'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 100, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 100, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'refInit', type: 'data-string', x: 100, y: 300, properties: { value: '' } },
      { id: 'ref', type: 'hook-useRef', x: 350, y: 300, properties: { name: 'inputRef' } },
      { id: 'ph', type: 'data-string', x: 350, y: 500, properties: { value: 'Champ avec ref' } },
      { id: 'input', type: 'ui-input', x: 600, y: 250, properties: {} },
      { id: 'focusLabel', type: 'data-string', x: 600, y: 500, properties: { value: 'Focus' } },
      { id: 'focusBtn', type: 'ui-button', x: 850, y: 400, properties: { variant: 'secondary' } },
      { id: 'log', type: 'debug-log', x: 1100, y: 400, properties: {} },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'input', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'focusBtn', toPortIndex: 0 },
      { fromNode: 'refInit', fromPortIndex: 0, toNode: 'ref', toPortIndex: 0 },
      { fromNode: 'ph', fromPortIndex: 0, toNode: 'input', toPortIndex: 1 },
      { fromNode: 'focusLabel', fromPortIndex: 0, toNode: 'focusBtn', toPortIndex: 1 },
      { fromNode: 'focusBtn', fromPortIndex: 0, toNode: 'log', toPortIndex: 0 },
      { fromNode: 'ref', fromPortIndex: 1, toNode: 'log', toPortIndex: 1 },
    ],
  },

  {
    id: 'use-memo-calc',
    name: 'useMemo Calcul',
    description: 'Optimiser les calculs coûteux',
    category: 'state',
    difficulty: 'advanced',
    tags: ['useMemo', 'optimisation', 'performance'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 100, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 100, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'numInit', type: 'data-number', x: 100, y: 300, properties: { value: 5 } },
      { id: 'numState', type: 'hook-useState', x: 350, y: 300, properties: { name: 'number' } },
      { id: 'mult', type: 'math-multiply', x: 600, y: 350, properties: {} },
      { id: 'label', type: 'data-string', x: 600, y: 550, properties: { value: 'Le carré est: ' } },
      { id: 'concat', type: 'data-concat', x: 850, y: 450, properties: {} },
      { id: 'result', type: 'ui-text', x: 1100, y: 350, properties: { tag: 'h2' } },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'result', toPortIndex: 0 },
      { fromNode: 'numInit', fromPortIndex: 0, toNode: 'numState', toPortIndex: 0 },
      { fromNode: 'numState', fromPortIndex: 0, toNode: 'mult', toPortIndex: 0 },
      { fromNode: 'numState', fromPortIndex: 0, toNode: 'mult', toPortIndex: 1 },
      { fromNode: 'label', fromPortIndex: 0, toNode: 'concat', toPortIndex: 0 },
      { fromNode: 'mult', fromPortIndex: 0, toNode: 'concat', toPortIndex: 1 },
      { fromNode: 'concat', fromPortIndex: 0, toNode: 'result', toPortIndex: 1 },
    ],
  },

  {
    id: 'use-effect-lifecycle',
    name: 'useEffect Lifecycle',
    description: 'Gérer le cycle de vie du composant',
    category: 'state',
    difficulty: 'advanced',
    tags: ['useEffect', 'lifecycle', 'montage'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 100, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 100, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'title', type: 'data-string', x: 100, y: 300, properties: { value: 'Cycle de vie' } },
      { id: 'titleUi', type: 'ui-text', x: 350, y: 250, properties: { tag: 'h2' } },
      { id: 'deps', type: 'data-array', x: 100, y: 450, properties: {} },
      { id: 'effect', type: 'hook-useEffect', x: 350, y: 450, properties: {} },
      { id: 'mountMsg', type: 'data-string', x: 350, y: 650, properties: { value: 'Composant monté!' } },
      { id: 'mountLog', type: 'debug-log', x: 600, y: 350, properties: {} },
      { id: 'info', type: 'data-string', x: 600, y: 550, properties: { value: 'Vérifiez la console' } },
      { id: 'infoUi', type: 'ui-text', x: 850, y: 450, properties: { tag: 'p' } },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'titleUi', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'infoUi', toPortIndex: 0 },
      { fromNode: 'title', fromPortIndex: 0, toNode: 'titleUi', toPortIndex: 1 },
      { fromNode: 'deps', fromPortIndex: 0, toNode: 'effect', toPortIndex: 0 },
      { fromNode: 'effect', fromPortIndex: 0, toNode: 'mountLog', toPortIndex: 0 },
      { fromNode: 'mountMsg', fromPortIndex: 0, toNode: 'mountLog', toPortIndex: 1 },
      { fromNode: 'info', fromPortIndex: 0, toNode: 'infoUi', toPortIndex: 1 },
    ],
  },

  // =============== APPS (28-30) ===============
  {
    id: 'todo-app',
    name: 'Todo App',
    description: 'Application complète de gestion de tâches',
    category: 'apps',
    difficulty: 'advanced',
    tags: ['todo', 'CRUD', 'application'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 100, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 100, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'title', type: 'data-string', x: 100, y: 250, properties: { value: '📝 Ma Todo Liste' } },
      { id: 'titleUi', type: 'ui-text', x: 350, y: 250, properties: { tag: 'h1' } },
      { id: 'todo1', type: 'data-string', x: 50, y: 400, properties: { value: 'Acheter du pain' } },
      { id: 'todo2', type: 'data-string', x: 50, y: 500, properties: { value: 'Appeler maman' } },
      { id: 'todosInit', type: 'data-array', x: 200, y: 450, properties: {} },
      { id: 'todosState', type: 'hook-useState', x: 400, y: 400, properties: { name: 'todos' } },
      { id: 'list', type: 'ui-list', x: 650, y: 350, properties: {} },
      { id: 'inputRow', type: 'ui-container', x: 650, y: 550, properties: { layout: 'flex-row', gap: 2 } },
      { id: 'newInit', type: 'data-string', x: 100, y: 650, properties: { value: '' } },
      { id: 'newState', type: 'hook-useState', x: 350, y: 650, properties: { name: 'newTodo' } },
      { id: 'inputPh', type: 'data-string', x: 350, y: 800, properties: { value: 'Nouvelle tâche...' } },
      { id: 'input', type: 'ui-input', x: 900, y: 500, properties: {} },
      { id: 'addLabel', type: 'data-string', x: 900, y: 700, properties: { value: 'Ajouter' } },
      { id: 'addBtn', type: 'ui-button', x: 1150, y: 600, properties: { variant: 'primary' } },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'titleUi', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'list', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'inputRow', toPortIndex: 0 },
      { fromNode: 'inputRow', fromPortIndex: 0, toNode: 'input', toPortIndex: 0 },
      { fromNode: 'inputRow', fromPortIndex: 0, toNode: 'addBtn', toPortIndex: 0 },
      { fromNode: 'title', fromPortIndex: 0, toNode: 'titleUi', toPortIndex: 1 },
      { fromNode: 'todo1', fromPortIndex: 0, toNode: 'todosInit', toPortIndex: 0 },
      { fromNode: 'todo2', fromPortIndex: 0, toNode: 'todosInit', toPortIndex: 1 },
      { fromNode: 'todosInit', fromPortIndex: 0, toNode: 'todosState', toPortIndex: 0 },
      { fromNode: 'todosState', fromPortIndex: 0, toNode: 'list', toPortIndex: 1 },
      { fromNode: 'newInit', fromPortIndex: 0, toNode: 'newState', toPortIndex: 0 },
      { fromNode: 'inputPh', fromPortIndex: 0, toNode: 'input', toPortIndex: 1 },
      { fromNode: 'newState', fromPortIndex: 0, toNode: 'input', toPortIndex: 2 },
      { fromNode: 'addLabel', fromPortIndex: 0, toNode: 'addBtn', toPortIndex: 1 },
    ],
  },

  {
    id: 'calculator',
    name: 'Calculatrice',
    description: 'Calculatrice avec les 4 opérations',
    category: 'apps',
    difficulty: 'advanced',
    tags: ['calculatrice', 'math', 'opérations'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 100, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 100, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'title', type: 'data-string', x: 100, y: 250, properties: { value: '🔢 Calculatrice' } },
      { id: 'titleUi', type: 'ui-text', x: 350, y: 250, properties: { tag: 'h1' } },
      { id: 'aInit', type: 'data-number', x: 100, y: 400, properties: { value: 0 } },
      { id: 'aState', type: 'hook-useState', x: 350, y: 400, properties: { name: 'a' } },
      { id: 'aPh', type: 'data-string', x: 350, y: 550, properties: { value: 'Nombre A' } },
      { id: 'aInput', type: 'ui-input', x: 600, y: 350, properties: {} },
      { id: 'bInit', type: 'data-number', x: 100, y: 700, properties: { value: 0 } },
      { id: 'bState', type: 'hook-useState', x: 350, y: 700, properties: { name: 'b' } },
      { id: 'bPh', type: 'data-string', x: 350, y: 850, properties: { value: 'Nombre B' } },
      { id: 'bInput', type: 'ui-input', x: 600, y: 650, properties: {} },
      { id: 'add', type: 'math-add', x: 850, y: 350, properties: {} },
      { id: 'addLabel', type: 'data-string', x: 850, y: 200, properties: { value: 'A + B = ' } },
      { id: 'addConcat', type: 'data-concat', x: 1100, y: 250, properties: {} },
      { id: 'addText', type: 'ui-text', x: 1350, y: 250, properties: { tag: 'p' } },
      { id: 'sub', type: 'math-subtract', x: 850, y: 500, properties: {} },
      { id: 'subLabel', type: 'data-string', x: 850, y: 650, properties: { value: 'A - B = ' } },
      { id: 'subConcat', type: 'data-concat', x: 1100, y: 550, properties: {} },
      { id: 'subText', type: 'ui-text', x: 1350, y: 550, properties: { tag: 'p' } },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'titleUi', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'aInput', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'bInput', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'addText', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'subText', toPortIndex: 0 },
      { fromNode: 'title', fromPortIndex: 0, toNode: 'titleUi', toPortIndex: 1 },
      { fromNode: 'aInit', fromPortIndex: 0, toNode: 'aState', toPortIndex: 0 },
      { fromNode: 'aPh', fromPortIndex: 0, toNode: 'aInput', toPortIndex: 1 },
      { fromNode: 'aState', fromPortIndex: 0, toNode: 'aInput', toPortIndex: 2 },
      { fromNode: 'bInit', fromPortIndex: 0, toNode: 'bState', toPortIndex: 0 },
      { fromNode: 'bPh', fromPortIndex: 0, toNode: 'bInput', toPortIndex: 1 },
      { fromNode: 'bState', fromPortIndex: 0, toNode: 'bInput', toPortIndex: 2 },
      { fromNode: 'aState', fromPortIndex: 0, toNode: 'add', toPortIndex: 0 },
      { fromNode: 'bState', fromPortIndex: 0, toNode: 'add', toPortIndex: 1 },
      { fromNode: 'addLabel', fromPortIndex: 0, toNode: 'addConcat', toPortIndex: 0 },
      { fromNode: 'add', fromPortIndex: 0, toNode: 'addConcat', toPortIndex: 1 },
      { fromNode: 'addConcat', fromPortIndex: 0, toNode: 'addText', toPortIndex: 1 },
      { fromNode: 'aState', fromPortIndex: 0, toNode: 'sub', toPortIndex: 0 },
      { fromNode: 'bState', fromPortIndex: 0, toNode: 'sub', toPortIndex: 1 },
      { fromNode: 'subLabel', fromPortIndex: 0, toNode: 'subConcat', toPortIndex: 0 },
      { fromNode: 'sub', fromPortIndex: 0, toNode: 'subConcat', toPortIndex: 1 },
      { fromNode: 'subConcat', fromPortIndex: 0, toNode: 'subText', toPortIndex: 1 },
    ],
  },

  {
    id: 'entity-system',
    name: 'Entités & Méthodes',
    description: 'Système OOP avec entités et méthodes',
    category: 'apps',
    difficulty: 'advanced',
    tags: ['entité', 'OOP', 'méthode', 'classe'],
    nodes: [
      { id: 'start', type: 'event-start', x: 100, y: 100, properties: {} },
      { id: 'container', type: 'ui-container', x: 350, y: 100, properties: { layout: 'flex-col', gap: 4 } },
      { id: 'title', type: 'data-string', x: 100, y: 250, properties: { value: '👤 Gestion Utilisateur' } },
      { id: 'titleUi', type: 'ui-text', x: 350, y: 250, properties: { tag: 'h1' } },
      { id: 'nameLabel', type: 'data-string', x: 100, y: 400, properties: { value: 'Nom: John Doe' } },
      { id: 'nameUi', type: 'ui-text', x: 350, y: 400, properties: { tag: 'p' } },
      { id: 'ageLabel', type: 'data-string', x: 100, y: 550, properties: { value: 'Âge: 25 ans' } },
      { id: 'ageUi', type: 'ui-text', x: 350, y: 550, properties: { tag: 'p' } },
      { id: 'btnLabel', type: 'data-string', x: 350, y: 700, properties: { value: 'Mettre à jour' } },
      { id: 'btn', type: 'ui-button', x: 600, y: 650, properties: { variant: 'primary' } },
      { id: 'log', type: 'debug-log', x: 850, y: 650, properties: {} },
      { id: 'logMsg', type: 'data-string', x: 850, y: 800, properties: { value: 'Utilisateur mis à jour!' } },
    ],
    connections: [
      { fromNode: 'start', fromPortIndex: 0, toNode: 'container', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'titleUi', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'nameUi', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'ageUi', toPortIndex: 0 },
      { fromNode: 'container', fromPortIndex: 0, toNode: 'btn', toPortIndex: 0 },
      { fromNode: 'title', fromPortIndex: 0, toNode: 'titleUi', toPortIndex: 1 },
      { fromNode: 'nameLabel', fromPortIndex: 0, toNode: 'nameUi', toPortIndex: 1 },
      { fromNode: 'ageLabel', fromPortIndex: 0, toNode: 'ageUi', toPortIndex: 1 },
      { fromNode: 'btnLabel', fromPortIndex: 0, toNode: 'btn', toPortIndex: 1 },
      { fromNode: 'btn', fromPortIndex: 0, toNode: 'log', toPortIndex: 0 },
      { fromNode: 'logMsg', fromPortIndex: 0, toNode: 'log', toPortIndex: 1 },
    ],
  },
];

export const getTemplatesByCategory = (category: Template['category']): Template[] => {
  return TEMPLATES.filter(t => t.category === category);
};

export const getTemplatesByDifficulty = (difficulty: Template['difficulty']): Template[] => {
  return TEMPLATES.filter(t => t.difficulty === difficulty);
};

export const searchTemplates = (query: string): Template[] => {
  const q = query.toLowerCase();
  return TEMPLATES.filter(
    t =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.tags.some(tag => tag.toLowerCase().includes(q))
  );
};
